spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/shopflow
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  jwt:
    secret: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7e3d90d9b7f3d26a7b9f1c4e2d
    expiration-ms: 86400000  # 24 hours