create table outbox_events (
                               id bigint generated by default as identity primary key,
                               event_type varchar(255) not null,
                               email varchar(255) not null,
                               order_id varchar(255) not null,
                               amount decimal(10, 2) not null,
                               processed boolean not null,
                               created_at timestamp not null,
                               processed_at timestamp
);